apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-deployment
  template:
    metadata:
      labels:
        app: product-catalog-deployment
    spec:
      containers:
        - name: aws-ecr-spring-boot-category
          image: <act-id>.dkr.ecr.us-west-2.amazonaws.com/aws-ecr-spring-boot-product
          ports:
            - containerPort: 8081
            - containerPort: 8091
          env:
            - name: spring.profiles.active
              value: aws
          imagePullPolicy: Always